@php
    $whatsappNumber = preg_replace('/\D+/', '', (string) config('services.public_whatsapp.number', '+917451008842')) ?: '917451008842';
    $whatsappUrl = 'https://wa.me/'.$whatsappNumber.'?text='.rawurlencode('Hello Atlas, I have a question about app access.');
    $faqs = [
        ['category' => 'general', 'question' => 'What is Gym Atlas?', 'answer' => 'Gym Atlas is a connected fitness platform covering public gym discovery, gym operations, trainer workflows, and member fitness activity. Each role receives a separate, permission-aware experience while sharing the same underlying gym relationship.'],
        ['category' => 'member', 'question' => 'Can members find and contact gyms without signing in?', 'answer' => 'Yes. Approved public gyms can be searched on the website, and eligible profiles can accept structured contact or trial requests. Some in-app actions, such as favourites and ongoing account activity, require authentication.'],
        ['category' => 'access', 'question' => 'Can I use the Member App without joining a gym?', 'answer' => 'Yes. The Member App can be used independently for personal workouts, diet and progress tracking. If you later connect with a gym, available membership, attendance and trainer context can appear in the same app.'],
        ['category' => 'gym', 'question' => 'What can a gym manage?', 'answer' => 'The current Gym Admin covers branches, trainers, staff, members, plans, memberships, custom fees, payments, dues, attendance, announcements, reminders, trial requests, reports, settings, audit logs, and the public listing. Access depends on the user’s role and gym scope.'],
        ['category' => 'trainer', 'question' => 'What can trainers do in the Trainer App?', 'answer' => 'Trainers can use Atlas independently after account verification or through a connected gym. Verification is required before adding members or managing workout and diet plans. Available gym-connected features can also include assigned members, attendance context, notes, follow-ups, alerts and messaging.'],
        ['category' => 'member', 'question' => 'What can members track in the Member App?', 'answer' => 'Members can access their gym and membership context, trainer, attendance, workouts, workout history, diet plans, meal logs, weight, measurements, progress photos, notifications, trial requests, and other verified account features. Step tracking is available on supported Android devices when the required permissions and health services are available.'],
        ['category' => 'gym', 'question' => 'Does Atlas support more than one gym branch?', 'answer' => 'Yes. Gym operations and public information can include branch context. The exact actions available to a user remain limited by their assigned gym, branch, role, and permissions.'],
        ['category' => 'general', 'question' => 'Are all features on the marketing artwork literal app screens?', 'answer' => 'No. The website distinguishes real product screenshots from promotional illustrations. Product claims are based on verified current routes and screens; conceptual artwork is used only to explain an idea visually.'],
        ['category' => 'access', 'question' => 'How do gyms and trainers get access?', 'answer' => 'Gyms can submit an onboarding enquiry through the website. Trainers can register independently and complete account verification before adding members or managing plans, or they can follow a gym-connected invitation path. Atlas does not present a public trainer marketplace.'],
        ['category' => 'privacy', 'question' => 'How is private information handled on public pages?', 'answer' => 'Only approved public listing information is shown on public gym pages. Authenticated operational records remain protected by authentication, role, permission, gym, and branch boundaries. Refer to the Privacy Policy for the public data-handling overview.'],
        ['category' => 'privacy', 'question' => 'How can I ask for an Atlas account to be deleted?', 'answer' => 'Use the Account Deletion page to send an account-removal request to support. The team reviews the request and may contact you for information needed to identify the account and explain the applicable next steps.'],
    ];
    $faqStructuredData = ['@context' => 'https://schema.org', '@type' => 'FAQPage', 'mainEntity' => collect($faqs)->map(fn ($faq) => ['@type' => 'Question', 'name' => $faq['question'], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq['answer']]])->all()];
@endphp

<x-public.layouts.app page-title="Frequently Asked Questions" page-description="Answers about Gym Atlas gym discovery, member and trainer apps, gym operations, access, privacy and account deletion.">
    <x-slot:head><script type="application/ld+json">{!! json_encode($faqStructuredData, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script></x-slot:head>
    <section class="atlas-help-hero pb-20 pt-36 sm:pb-24 sm:pt-44">
        <div class="public-container relative z-10">
            <div class="max-w-4xl"><p class="public-kicker">Atlas knowledge desk</p><h1 class="mt-5 text-4xl font-semibold leading-[.98] tracking-[-.055em] text-slate-950 sm:text-6xl lg:text-7xl">Understand Atlas before choosing your next step.</h1><p class="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">Direct answers about discovery, membership, coaching, gym operations, access and trust—written around the decisions people actually need to make.</p></div>
            <label class="atlas-help-search" for="faq-search"><i class="ti ti-search text-xl text-brand-600" aria-hidden="true"></i><span class="sr-only">Search Atlas questions</span><input id="faq-search" type="search" placeholder="Search Atlas questions" autocomplete="off" data-faq-search><kbd data-faq-count>{{ count($faqs) }} answers</kbd></label>
        </div>
    </section>

    <section class="border-y border-slate-200 bg-white py-5"><div class="public-container"><div class="atlas-topic-rail" role="group" aria-label="Filter FAQ topics"><button type="button" data-faq-filter="all" aria-pressed="true">All questions</button><button type="button" data-faq-filter="member" aria-pressed="false">For members</button><button type="button" data-faq-filter="trainer" aria-pressed="false">For trainers</button><button type="button" data-faq-filter="gym" aria-pressed="false">For gyms</button><button type="button" data-faq-filter="access" aria-pressed="false">Access & permissions</button><button type="button" data-faq-filter="privacy" aria-pressed="false">Privacy & safety</button></div></div></section>

    <section id="questions" class="public-section scroll-mt-24 bg-slate-50">
        <div class="public-container grid gap-12 lg:grid-cols-[.32fr_.68fr]">
            <aside class="lg:sticky lg:top-28 lg:self-start"><p class="public-kicker">Knowledge hub</p><h2 class="mt-4 text-3xl font-semibold tracking-[-.04em] text-slate-950">Current product boundaries, in plain language.</h2><p class="mt-5 leading-8 text-slate-600">Members can begin independently. Trainers can also begin independently, with account verification required before adding members or managing plans; a gym-connected path remains available.</p><div class="mt-7 grid gap-3"><a href="{{ $whatsappUrl }}" target="_blank" rel="noopener noreferrer" class="public-button justify-center bg-[#25D366] text-white hover:bg-[#1fbd59]">Ask on WhatsApp</a><a href="{{ route('public.contact') }}" class="inline-flex items-center justify-center gap-2 font-semibold text-brand-600">Send a detailed enquiry <span aria-hidden="true">→</span></a></div></aside>
            <div class="atlas-faq-ledger rounded-[1.5rem] border border-slate-200 bg-white px-5 shadow-[0_28px_80px_rgba(15,23,42,.07)] sm:px-8">
                @foreach ($faqs as $faq)<details data-faq-item data-faq-category="{{ $faq['category'] }}" data-faq-text="{{ Str::lower($faq['question'].' '.$faq['answer']) }}"><summary><span>{{ $faq['question'] }}</span></summary><p class="atlas-faq-answer">{{ $faq['answer'] }}</p></details>@endforeach
                <div class="atlas-faq-empty" data-faq-empty hidden role="status"><i class="ti ti-search-off" aria-hidden="true"></i><strong>No matching answer yet.</strong><span>Try a broader phrase or contact the Atlas team for help.</span></div>
            </div>
        </div>
    </section>

    <section class="bg-slate-950 py-16 text-white"><div class="public-container grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold uppercase tracking-[.16em] text-cyan-300">Need a human answer?</p><h2 class="mt-3 text-3xl font-semibold tracking-[-.04em] text-white">Route your question to the right Atlas team.</h2><p class="mt-3 text-sm text-slate-400">WhatsApp Atlas at +91 74510 08842 or send a detailed enquiry.</p></div><div class="flex flex-col gap-3 sm:flex-row"><a href="{{ $whatsappUrl }}" target="_blank" rel="noopener noreferrer" class="public-button bg-[#25D366] text-white hover:bg-[#1fbd59]">WhatsApp Atlas</a><a href="{{ route('public.contact') }}" class="public-button public-button-primary">Contact Atlas</a></div></div></section>
</x-public.layouts.app>
