@extends('layouts.panel')

@section('content')
    <div class="space-y-6">
        <div><h2 class="text-2xl font-semibold text-slate-950 dark:text-white">Diet Plans</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Platform-wide oversight of gym, trainer, and member-created nutrition plans.</p></div>
        <div class="grid gap-3 md:grid-cols-3"><x-stat-card label="Visible plans" :value="$plans->total()" hint="Matching current filters" tone="sky" /><x-stat-card label="Active platform-wide" :value="$activeCount" hint="Currently available to members" tone="emerald" /><x-stat-card label="Personal plans" :value="$personalCount" hint="Member-created plans" tone="violet" /></div>
        <x-premium-card class="p-5"><form method="GET" class="grid gap-3 md:grid-cols-[1.2fr_0.8fr_0.7fr_auto]"><x-form-input name="search" label="Search" :value="request('search')" placeholder="Plan, gym, member..." /><div><label class="panel-label">Gym</label><select name="gym_id" class="panel-select"><option value="">All gyms</option>@foreach($gyms as $gym)<option value="{{ $gym->id }}" @selected((int) request('gym_id') === $gym->id)>{{ $gym->name }}</option>@endforeach</select></div><div><label class="panel-label">Status</label><select name="status" class="panel-select"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Paused</option></select></div><div class="flex items-end"><x-action-button type="submit" variant="secondary" class="w-full justify-center">Apply</x-action-button></div></form></x-premium-card>
        <x-table-wrapper><div class="overflow-x-auto"><table class="panel-table"><thead><tr><th>Plan</th><th>Gym / Branch</th><th>Member / Creator</th><th>Targets</th><th>Status</th></tr></thead><tbody>@forelse($plans as $plan)<tr><td><p class="font-medium text-slate-950 dark:text-white">{{ $plan->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $plan->meals->count() }} meals · {{ $plan->goal ?: 'No goal' }}</p></td><td>{{ $plan->gym?->name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $plan->branch?->name ?? 'Gym-wide' }}</span></td><td>{{ $plan->member?->name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $plan->trainer?->name ? 'Trainer: '.$plan->trainer->name : 'Personal / gym plan' }}</span></td><td>{{ $plan->daily_calorie_target ?? '—' }} kcal<br><span class="text-xs text-slate-500">P {{ $plan->protein_target_g ?? '—' }} · C {{ $plan->carbs_target_g ?? '—' }} · F {{ $plan->fats_target_g ?? '—' }}</span></td><td><x-status-badge :label="ucfirst($plan->status)" :tone="$plan->status === 'active' ? 'success' : 'warning'" /><form method="POST" class="mt-2" action="{{ route('web.admin.diet-plans.status', $plan) }}">@csrf<input type="hidden" name="status" value="{{ $plan->status === 'active' ? 'inactive' : 'active' }}"><x-action-button type="submit" variant="secondary">{{ $plan->status === 'active' ? 'Pause' : 'Resume' }}</x-action-button></form></td></tr>@empty<tr><td colspan="5"><x-empty-state title="No diet plans found" message="Adjust the filters to find plans across the platform." /></td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $plans->links() }}</div></x-table-wrapper>
    </div>
@endsection
