@extends('layouts.panel')

@section('content')
<div class="space-y-6">
    <section class="panel-hero overflow-hidden">@if($event->cover_image_url)<img src="{{ $event->cover_image_url }}" alt="{{ $event->title }}" class="mb-5 h-48 w-full rounded-2xl object-cover" loading="lazy">@endif<div class="panel-toolbar-chip">{{ ucfirst($event->status) }}</div><h2 class="mt-4 text-3xl font-semibold text-slate-950 dark:text-white">{{ $event->title }}</h2><p class="mt-2 text-sm text-slate-500">{{ $event->starts_at->timezone($event->timezone)->format('l, d M Y · g:i A') }} – {{ $event->ends_at->timezone($event->timezone)->format('g:i A') }} · {{ $event->location_name ?: 'Location not set' }}</p></section>
    <div class="grid gap-4 md:grid-cols-4"><x-stat-card label="Confirmed" :value="$event->confirmed_bookings_count" hint="active spots" tone="emerald"/><x-stat-card label="Waitlist" :value="$event->waitlisted_bookings_count" hint="queued by booking time" tone="amber"/><x-stat-card label="Attended" :value="$event->attended_bookings_count" hint="manual check-in" tone="sky"/><x-stat-card label="Capacity" :value="$event->capacity ?: 'Unlimited'" hint="maximum reservations" tone="violet"/></div>
    @if(in_array($event->status,['draft','published'],true))<div class="flex justify-end"><a class="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white" href="{{ $panel==='admin' ? route('web.admin.events.edit',$event) : route('web.gym.events.edit',array_merge(request()->only(['gym','branch']),['event'=>$event])) }}">Edit event</a></div>@endif
    @if($event->status === 'published')<x-premium-card class="p-5"><form method="POST" action="{{ $panel==='admin' ? route('web.admin.events.cancel',$event) : route('web.gym.events.cancel',array_merge(request()->only(['gym','branch']),['event'=>$event])) }}" class="flex flex-col gap-3 sm:flex-row">@csrf<input required name="reason" class="form-control min-w-0 flex-1" placeholder="Cancellation reason sent to attendees"><button class="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white">Cancel event</button></form></x-premium-card>@endif
    <x-table-wrapper class="overflow-hidden p-0"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h3 class="panel-section-title">Attendee and waitlist roster</h3></div><div class="overflow-x-auto"><table class="panel-table min-w-[800px]"><thead><tr><th>Member</th><th>Booked</th><th>Status</th><th>Attendance</th></tr></thead><tbody>
    @forelse($bookings as $booking)<tr><td><div class="font-semibold">{{ $booking->user->name }}</div><div class="text-xs text-slate-500">{{ $booking->user->email }} · {{ $booking->user->phone }}</div></td><td>{{ $booking->booked_at->format('d M Y, g:i A') }}</td><td><x-status-badge :label="$booking->status" /></td><td>@if(in_array($event->status,['published','completed'],true) && in_array($booking->status,['reserved','attended','no_show'],true) && now()->between($event->starts_at->copy()->subHours(2),$event->ends_at->copy()->addDay()))@php($attendanceRoute = $panel === 'admin' ? route('web.admin.events.attendance',['event'=>$event,'booking'=>$booking]) : route('web.gym.events.attendance',array_merge(request()->only(['gym','branch']),['event'=>$event,'booking'=>$booking])))<div class="flex gap-2"><form method="POST" action="{{ $attendanceRoute }}">@csrf @method('PUT')<input type="hidden" name="status" value="attended"><button class="text-sm font-semibold text-emerald-600">Attended</button></form><form method="POST" action="{{ $attendanceRoute }}">@csrf @method('PUT')<input type="hidden" name="status" value="no_show"><button class="text-sm font-semibold text-slate-500">No-show</button></form></div>@else<span class="text-xs text-slate-400">Not available</span>@endif</td></tr>
    @empty<tr><td colspan="4" class="py-10 text-center text-slate-500">No bookings yet.</td></tr>@endforelse
    </tbody></table></div><div class="p-4">{{ $bookings->withQueryString()->links() }}</div></x-table-wrapper>
</div>
@endsection
