@extends('layouts.panel')

@section('content')
    @section('page_actions')
        <x-action-button as="a" href="{{ route('web.admin.announcements.create') }}">Send Announcement</x-action-button>
    @endsection

    <div class="space-y-6">
        <section class="panel-hero">
            <div class="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
                <div class="max-w-3xl">
                    <div class="panel-toolbar-chip">Delivery Ledger</div>
                    <h2 class="mt-4 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Notifications</h2>
                    <p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Audit notification delivery generated by announcements, billing reminders, and platform automation from a quieter, searchable operator surface.</p>
                </div>
                <div class="admin-detail-grid-compact w-full xl:max-w-xl">
                    <div class="panel-card-muted px-4 py-4">
                        <div class="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">Unread</div>
                        <div class="mt-2 text-lg font-semibold text-slate-950 dark:text-white">{{ $unreadNotificationsCount }}</div>
                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">delivery records not opened yet</div>
                    </div>
                    <div class="panel-card-muted px-4 py-4">
                        <div class="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">Scheduled</div>
                        <div class="mt-2 text-lg font-semibold text-slate-950 dark:text-white">{{ $scheduledCount }}</div>
                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">notifications with scheduled timestamps</div>
                    </div>
                </div>
            </div>
        </section>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <x-stat-card label="Notifications" :value="$notifications->total()" hint="Matching records" tone="sky" />
            <x-stat-card label="Unread" :value="$unreadNotificationsCount" hint="Pending opens" tone="amber" />
            <x-stat-card label="Types" :value="count($notificationTypes)" hint="Distinct delivery categories" tone="violet" />
            <x-stat-card label="Loaded" :value="$notifications->count()" hint="Visible on this page" tone="emerald" />
        </div>

        <x-premium-card class="p-5">
            <form method="GET" class="grid gap-4 md:grid-cols-[minmax(0,1.8fr)_minmax(220px,1fr)_minmax(220px,1fr)_auto]">
                <x-form-input name="search" label="Search" :value="request('search')" placeholder="Search title, copy, or recipient" />
                <x-form-select name="type" label="Type" :selected="request('type')">
                    <option value="">All types</option>
                    @foreach ($notificationTypes as $type)
                        <option value="{{ $type }}" @selected(request('type') === $type)>{{ str($type)->replace('_', ' ')->title() }}</option>
                    @endforeach
                </x-form-select>
                <x-form-select name="status" label="Read Status" :selected="request('status')" :options="['' => 'All statuses', 'unread' => 'Unread', 'read' => 'Read']" />
                <div class="flex items-end gap-2">
                    <x-action-button type="submit">Apply Filters</x-action-button>
                    <x-action-button as="a" href="{{ route('web.admin.notifications.index') }}" variant="secondary">Reset</x-action-button>
                </div>
            </form>
        </x-premium-card>

        <x-table-wrapper class="overflow-hidden p-0">
            <div class="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 md:flex-row md:items-center md:justify-between dark:border-slate-800">
                <div>
                    <h3 class="panel-section-title">Notification Records</h3>
                    <p class="panel-section-copy">Track who received what, where it came from, and whether it has been opened.</p>
                </div>
                <x-status-badge :label="$notifications->total().' total'" tone="neutral" />
            </div>

            @if ($notifications->count() > 0)
                <div class="overflow-x-auto">
                    <table class="panel-table min-w-[1320px]">
                        <thead>
                            <tr>
                                <th>Message</th>
                                <th>Recipient</th>
                                <th>Scope</th>
                                <th>Source</th>
                                <th>Lifecycle</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($notifications as $notification)
                                <tr>
                                    <td>
                                        <div class="flex flex-wrap items-center gap-2">
                                            <div class="font-semibold text-slate-950 dark:text-white">{{ $notification->title }}</div>
                                            <x-status-badge :label="$notification->read_at ? 'Read' : 'Unread'" :tone="$notification->read_at ? 'success' : 'warning'" />
                                            <x-status-badge :label="str($notification->type)->replace('_', ' ')->title()" tone="info" />
                                        </div>
                                        <div class="mt-2 text-sm text-slate-600 dark:text-slate-300">{{ \Illuminate\Support\Str::limit($notification->body ?: $notification->message, 140) }}</div>
                                    </td>
                                    <td class="text-sm text-slate-600 dark:text-slate-300">
                                        <div>{{ $notification->user?->name ?? 'Unknown user' }}</div>
                                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ $notification->user?->email ?? 'No email recorded' }}</div>
                                    </td>
                                    <td class="text-sm text-slate-600 dark:text-slate-300">
                                        <div>{{ $notification->gym?->name ?? 'Platform wide' }}</div>
                                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ $notification->branch?->name ?? 'No branch restriction' }}</div>
                                    </td>
                                    <td class="text-sm text-slate-600 dark:text-slate-300">
                                        <div>{{ $notification->creator?->name ?? 'System' }}</div>
                                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">
                                            @if ($notification->announcement)
                                                Announcement #{{ $notification->announcement->id }}
                                            @elseif ($notification->member_membership_id)
                                                Membership #{{ $notification->member_membership_id }}
                                            @else
                                                Internal event
                                            @endif
                                        </div>
                                    </td>
                                    <td class="text-sm text-slate-600 dark:text-slate-300">
                                        <div>Created {{ optional($notification->created_at)->format('d M Y, h:i A') ?: '--' }}</div>
                                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">Scheduled {{ optional($notification->scheduled_for)->format('d M Y, h:i A') ?: 'Immediate' }}</div>
                                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">Read {{ optional($notification->read_at)->format('d M Y, h:i A') ?: 'Not opened' }}</div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <div class="p-5">
                    <x-empty-state title="No notifications found" message="Delivery records will appear here as users receive platform, billing, and communication updates." />
                </div>
            @endif

            @if ($notifications->hasPages())
                <div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">
                    {{ $notifications->links() }}
                </div>
            @endif
        </x-table-wrapper>
    </div>
@endsection
