<?php

namespace App\Http\Resources\Workout;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class WorkoutSessionResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'gym_id' => $this->gym_id,
            'branch_id' => $this->branch_id,
            'member_id' => $this->member_id,
            'trainer_id' => $this->trainer_id,
            'workout_plan_id' => $this->workout_plan_id,
            'workout_plan_day_id' => $this->workout_plan_day_id,
            'workout_schedule_override_id' => $this->workout_schedule_override_id,
            'source_import_batch_id' => $this->source_import_batch_id,
            'source_external_id' => $this->source_external_id,
            'plan_day_number' => $this->plan_day_number,
            'plan_day_label' => $this->plan_day_label,
            'day_selection_mode' => $this->day_selection_mode,
            'session_date' => $this->session_date?->toDateString(),
            'status' => $this->status,
            'started_at' => $this->started_at?->toIso8601String(),
            'completed_at' => $this->completed_at?->toIso8601String(),
            'last_activity_at' => $this->last_activity_at?->toIso8601String(),
            'notes' => $this->notes,
            'pre_workout_weight_kg' => $this->pre_workout_weight_kg !== null ? (float) $this->pre_workout_weight_kg : null,
            'total_volume' => (float) $this->total_volume,
            'completion_summary' => $this->completion_summary,
            'runtime_state' => $this->runtime_state,
            'exercises' => $this->whenLoaded('exercises', fn () => $this->exercises->map(fn ($exercise) => [
                'id' => $exercise->id,
                'workout_plan_exercise_id' => $exercise->workout_plan_exercise_id,
                'exercise_id' => $exercise->exercise_id,
                'exercise' => ExerciseResource::make($exercise->exercise),
                'sort_order' => $exercise->sort_order,
                'planned_sets' => $exercise->planned_sets,
                'tracking_mode' => $exercise->tracking_mode ?? 'reps',
                'planned_reps' => $exercise->planned_reps,
                'planned_duration_seconds' => $exercise->planned_duration_seconds,
                'planned_distance_meters' => $exercise->planned_distance_meters !== null ? (float) $exercise->planned_distance_meters : null,
                'planned_speed_kph' => $exercise->planned_speed_kph !== null ? (float) $exercise->planned_speed_kph : null,
                'planned_pace_seconds_per_km' => $exercise->planned_pace_seconds_per_km,
                'target_weight' => (float) ($exercise->target_weight ?? 0),
                'target_resistance' => $exercise->target_resistance !== null ? (float) $exercise->target_resistance : null,
                'target_machine_level' => $exercise->target_machine_level !== null ? (float) $exercise->target_machine_level : null,
                'is_per_side' => (bool) $exercise->is_per_side,
                'is_bodyweight' => (bool) $exercise->is_bodyweight,
                'performed_status' => $exercise->performed_status,
                'substituted_for_session_exercise_id' => $exercise->substituted_for_session_exercise_id,
                'rest_timer_seconds' => $exercise->rest_timer_seconds,
                'group_key' => $exercise->group_key,
                'group_type' => $exercise->group_type,
                'group_order' => $exercise->group_order,
                'group_rounds' => $exercise->group_rounds,
                'transition_seconds' => $exercise->transition_seconds,
                'rest_after' => $exercise->rest_after,
                'progression_policy' => $exercise->progression_policy ?? 'off',
                'progression_config' => $exercise->progression_config,
                'progression_version' => $exercise->progression_version ?? 1,
                'progression_recommendation_id' => $exercise->progression_recommendation_id,
                'progression_explanation' => $exercise->progression_explanation,
                'notes' => $exercise->notes,
                'sets' => $exercise->sets->map(fn ($set) => [
                    'id' => $set->id,
                    'set_number' => $set->set_number,
                    'reps' => $set->reps,
                    'duration_seconds' => $set->duration_seconds,
                    'distance_meters' => $set->distance_meters !== null ? (float) $set->distance_meters : null,
                    'speed_kph' => $set->speed_kph !== null ? (float) $set->speed_kph : null,
                    'pace_seconds_per_km' => $set->pace_seconds_per_km,
                    'weight' => (float) $set->weight,
                    'rest_seconds' => $set->rest_seconds,
                    'effort_scale' => $set->effort_scale,
                    'effort_value' => $set->effort_value !== null ? (float) $set->effort_value : null,
                    'side' => $set->side,
                    'notes' => $set->notes,
                    'is_completed' => $set->is_completed,
                    'completed_at' => $set->completed_at?->toIso8601String(),
                ])->values(),
            ])->values()),
            'created_at' => $this->created_at?->toIso8601String(),
            'updated_at' => $this->updated_at?->toIso8601String(),
        ];
    }
}
